### ISSUE TITLE
Implement wit.ai (ML)

### ISSUE THREAD

**Issue by gaassassins** [esikachev/project-411#11]
There is a great toolkit for implement machine learning (https://wit.ai) to our chatbot

**Comment by rkhozinov** [comment]
Do you have experience of usage the toolkit?
Which purposes do you want to achieve by the toolkit?
If you have an answer - please decompose the issue for productive team discussion.

But now it seems like HDD.

**Comment by rkhozinov** [comment]
It seems you have a problem with priorities.
24 days without any discussion and pull-requests for the P0-issue - it isn't good.

**Comment by nikitabelonogov** [comment]
Using of wit.ai was rejected as I know.

**Comment by rkhozinov** [comment]
@gaassasins if so - please close the issue
