### ISSUE TITLE
Researching of libs for AI

### ISSUE THREAD

**Issue by esikachev** [esikachev/project-411#18]
deadline: 02.02.2017 23:59

**Comment by gaassassins** [comment]
I'm doing some research and if we want to use something like flask on backend of our project, for AI in chatbot core we can use [NLTK](http://www.nltk.org). It is provides a practical introduction to programming for language processing. Exactly what we needed. So we can use [spaCy](https://spacy.io) and TextBlob library also.

**Comment by esikachev** [comment]
@nikitabelonogov @zemuvier @gotay94 any updates?

**Comment by rkhozinov** [comment]
@gaassassins Mary please provide your results. 
The issue is a cornerstone of your project, but it hasn't been resolved after ~20 days after creation. 
Who is really responsible for the issue?
