### ISSUE TITLE
Implement CI

### ISSUE THREAD

**Issue by nikitabelonogov** [esikachev/project-411#2]
pull requests must be automatically tested

**Comment by gaassassins** [comment]
https://pythonhosted.org/Flask-CI/

**Comment by esikachev** [comment]
@gaassassins are you sure? 0 downloads... It's strange...

**Comment by zemuvier** [comment]
Let's use Travis CI https://travis-ci.com because it's free

**Comment by gaassassins** [comment]
We can use jenkins also

**Comment by esikachev** [comment]
@gaassassins do you have a host for jenkins?

**Comment by zemuvier** [comment]
We need basic CI to test pep8 and py27 for the beginning. In my opinion, it's better ti use Travis CI because it's implemented on GitHub for free  https://docs.travis-ci.com/user/getting-started
