### ISSUE TITLE
Create many-to-many relationship table

### ISSUE THREAD

**Issue by gaassassins** [esikachev/project-411#27]
keywords
32 hi
33 hello
34 hey

responses
1009 hi, how r u nah
1037 nice to meet you, buddy

and we need to create table that looks like
keyword_responses
32 1009
32 1039

**Comment by rkhozinov** [comment]
Please describe the task's details more properly.
If possible, pls move you proposal to comments to start discussion about possible solutions.

When we propose a solution in the task - it could confuse collaborators and limit the number of possible solutions.

**Comment by rkhozinov** [comment]
Does heroku support only sql dbs?

**Comment by rkhozinov** [comment]
Does it related to #14 ?

**Comment by rkhozinov** [comment]
It seems that heroku supports redis (https://elements.heroku.com/addons/heroku-redis)
