### ISSUE TITLE
HTML injections bug

### ISSUE THREAD

**Issue by nikitabelonogov** [esikachev/project-411#30]
user can send message such as <a href="javascript:alert("alert");">a</a>

**Comment by rkhozinov** [comment]
Is it security issue?
If you think so, please raise up its priority.

**Comment by rkhozinov** [comment]
@nikitabelonogov please rename issue to **HTML injections bug** to coincide to others

**Comment by rkhozinov** [comment]
@gaassassins @nikitabelonogov how do you plan to fix that? Who is responsible for back/front solutions?

**Comment by gaassassins** [comment]
@rkhozinov we have UI-developer for this bugfix but he is on vacation in a few days so

**Comment by rkhozinov** [comment]
Are you sure that only frontend fix is enough? 
opensource project is transparent and a potentially attacker could find workaround for the frontend fix and use the vulnerability. 

Anyway, bus factor = 1 - isn’t good. I think UI support could be managed by the team, especially if it security issue, affecting some parts of your app.

**Comment by nikitabelonogov** [comment]
ETA: 4d (5.3.17)

**Comment by anton950712** [comment]
@nikitabelonogov BLOCKER

**Comment by gaassassins** [comment]
close #52
