### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by zemuvier** [esikachev/project-411#37]
We need to create Readme file with:

1. User doc:
- What is our product is
- How to install an run it (quickstart)

2. Advanced doc:
- Which technologies do we use (and maybe what we want to use)
- How to become a contributor of this project
- How to run tests
- How to run this project with specific configuration 

etc

**Comment by zemuvier** [comment]
@gaassassins @nikitabelonogov let me know what you think will be useful to add too

**Comment by rkhozinov** [comment]
> Everybody's business is nobody's business
So, assignee should be one per task, and rest of the team should be set as reviewers for a PR if it needed.

If you want to share this issue between team - please decompose the task and find assignee with required skills. It should be discussed on the planning before an iteration. 

For example: 

User doc:

- What is our product is @gaassassins 
- How to install an run it (quickstart) @nikitabelonogov 

Advanced doc:

10. Which technologies do we use (and maybe what we want to use) <- also should be decomposed

- frontend @anton950712 
- back @gaassassins 
- deploy @nikitabelonogov 
- test methodologies and frameworks @zemuvier 

20. How to become a contributor of this project @zemuvier 
30. How to run tests @zemuvier 
40. How to run this project with specific configuration @nikitabelonogov

**Comment by gaassassins** [comment]
close #58
