### ISSUE TITLE
Describe a legend for priorities

### ISSUE THREAD

**Issue by rkhozinov** [esikachev/project-411#46]
If you using a special standard for priorities in your project - describe it in the Readme file (Contributors guide). 

P0-n priorities notation could confuse collaborators, you could try best practices from open-source world to avoid misunderstandings between collaborators, for example Launchpad's bug priorities for bugs in your project.

Also need to set limits to fix critical, high, low issues and bugs. It doesn't look good if a critical issue won't be fixed for a whole week.

For issues' priorities you could try to review some large projects on the GitHub and apply theirs flow for your project. 

> Steal like an artist

**Comment by rkhozinov** [comment]
@zemuvier @gaassassins @nikitabelonogov pls manage it

**Comment by gaassassins** [comment]
@rkhozinov thanks! we are already doing this.
